filePaths:
  proxies: './proxies.txt'
  accounts: './accounts.txt'
  fingerprints: './fingerprints.db'
  

server:
  port: 3000
  logLevel: 'debug'

task: 
  privateKey: 'test'
  youtubeChannel:
    isRequired: true
    addBio: true
    addLogo: true

smsService: 
  name: 5sim
  apiKey: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDkxODU5NzIsImlhdCI6MTcxNzY0OTk3MiwicmF5IjoiZDI1NWEwMmRhMDZkZjdmNzgwYTQ5NGY2ZGViMTA3MTgiLCJzdWIiOjIzMjE2NjF9.H3nHY-NAIELz0KA-Q2m5Efpw9_ASohZ4EUbJbNFT6Qdf5DsBwIXO_BMcxwOV3RHaWoMzA_le7Vi50bovjo3Q0UNFIj0I9dGOXhSlFV-oPUo54oIDSOWRSrR32x_64e8n5hgqsVsu4DfE-KX_oYW7ZPywjDTKG4kPky7hCqtueFbYCF8VcGC8r7ABST6SuwzxQhlQEuzlcO8QEp-UEp-cNAmg47SPiKgGRUfeBX57tGNCCm0gegd9p43daNe1DwbAv4l55rddtcWNTslEuDtlCSc7rrhB3JZ5VfGUHtklwoqznpCE47H7on09Wi0Psmm6-SjLN_JFfi_hM3T2PQFB0g
  country: india
  maxPrice: 6
